[theme]
primaryColor = "#F4A261" # Warna tombol pastel
backgroundColor = "#FAFAFA" # Background putih bersih
secondaryBackgroundColor = "#F0EAE6" # Elemen abu-abu/nude lembut
textColor = "#2B2B2B"
font = "sans serif"
